# Tự động Deploy lên GitHub Pages bằng GitHub Actions
name: Deploy static content to Pages

on:
  # Chạy khi push code lên nhánh main
  push:
    branches: ["main"]

  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Cấp quyền cho GITHUB_TOKEN để được phép ghi lên GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép deploy 1 lần tại 1 thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job Deploy duy nhất
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload toàn bộ thư mục root
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
